api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

# urlpatterns = [
    # path('ayakkabi/', views.AyakkabiList.as_view()),
    # path('ayakkabi/<int:pk>/', views.AyakkabiDetail.as_view()),
# ]

# urlpatterns = format_suffix_patterns(urlpatterns)

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.anasayfa, name='anasayfa'),
    path('arama/', views.arama, name='arama'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('lisans/', views.lisans, name='lisans'),
    path('hesap/', views.hesap, name='hesap'),
    path('sifredegistir/', views.sifredegistir, name='sifredegistir'),
    path('koli/eklecikar/', views.kolieklecikar, name='kolieklecikar'),
    path('koli/sil/<int:pk>/', views.kolieklecikar_sil, name='kolieklecikar_sil'),
    path('koli/', views.kolirapor, name='kolirapor'),
    path('koli/guncelle/', views.koliguncelle, name='koliguncelle'),
    path('koli/detay/<str:urun>', views.kolirapor_tek_detay, name='kolirapor_tek_detay'),
    path('hammadde/eklecikar/', views.hammaddeeklecikar, name='hammaddeeklecikar'),
    path('hammadde/sil/<int:pk>/', views.hammaddeeklecikar_sil, name='hammaddeeklecikar_sil'),
    path('hammadde/', views.hammadderapor, name='hammadderapor'),
    path('hammadde/guncelle/', views.hammaddeguncelle, name='hammaddeguncelle'),
    path('yasak/', views.yasak, name='yasak'),
]

tsp_prj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('', include('dashboard.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='dashboard/login.html')),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
]

api/models.py
import pickle

from django import forms
from django.contrib.auth.models import User
from django.db import IntegrityError, models
from django.dispatch import receiver
from django.utils import timezone

from dashboard.methodpack import sorting_key, validate_package_type

# Mamuller:


class KoliSonDurum(models.Model):
    tarih = models.DateField(unique=True)
    KrepKisaKonc = models.BinaryField(blank=True, editable=True)
    KrepUzunKonc = models.BinaryField(blank=True, editable=True)
    KrepGarsonKisa = models.BinaryField(blank=True, editable=True)
    KrepGarsonUzun = models.BinaryField(blank=True, editable=True)
    KrepKahveBot = models.BinaryField(blank=True, editable=True)
    KrepSiyahBot = models.BinaryField(blank=True, editable=True)
    KrepCelikBurunluCizme = models.BinaryField(blank=True, editable=True)
    KasikCizme = models.BinaryField(blank=True, editable=True)
    FiletBezli = models.BinaryField(blank=True, editable=True)
    ZenneBezli = models.BinaryField(blank=True, editable=True)
    MerdaneBezli = models.BinaryField(blank=True, editable=True)
    MerdaneFanilali = models.BinaryField(blank=True, editable=True)
    ZenneIskarpin = models.BinaryField(blank=True, editable=True)
    MerdaneIskarpin = models.BinaryField(blank=True, editable=True)
    GarsonIskarpin = models.BinaryField(blank=True, editable=True)
    PresCizmeOB = models.BinaryField(blank=True, editable=True)
    PresCizmeS4 = models.BinaryField(blank=True, editable=True)
    PresCizmeS5 = models.BinaryField(blank=True, editable=True)
    ElektrikciOB = models.BinaryField(blank=True, editable=True)
    ElektrikciS4 = models.BinaryField(blank=True, editable=True)
    ElektrikciS5 = models.BinaryField(blank=True, editable=True)


class KoliDegisiklik(models.Model):
    MAMUL_SECENEKLERI = [
        ('Krep Çizme', (
            ('KrepKisaKonc', 'Krep Kısa Konç'),
            ('KrepUzunKonc', 'Krep Uzun Konç'),
            ('KrepGarsonKisa', 'Krep Garson Kısa'),
            ('KrepGarsonUzun', 'Krep Garson Uzun'),
            ('KrepKahveBot', 'Krep Kahve Bot'),
            ('KrepSiyahBot', 'Krep Siyah Bot'),
            ('KrepCelikBurunluCizme', 'Krep Çelik Burunlu Çizme'),
            ('KasikCizme', 'Kasık Çizme'),
        )
        ),
        ('Galoş Ayakkabı', (
            ('FiletBezli', 'Filet Bezli'),
            ('ZenneBezli', 'Zenne Bezli'),
            ('MerdaneBezli', 'Merdane Bezli'),
            ('MerdaneFanilali', 'Merdane Fanilalı'),
            ('ZenneIskarpin', 'Zenne İskarpin'),
            ('MerdaneIskarpin', 'Merdane İskarpin'),
            ('GarsonIskarpin', 'Garson İskarpin'),
        )
        ),
        ('Kobalt Çizme', (
            ('PresCizmeOB', 'Pres Çizme OB'),
            ('PresCizmeS4', 'Pres Çizme S4'),
            ('PresCizmeS5', 'Pres Çizme S5'),
            ('ElektrikciOB', 'Elektrikçi OB'),
            ('ElektrikciS4', 'Elektrikçi S4'),
            ('ElektrikciS5', 'Elektrikçi S5'),
        )
        ),
    ]

    KALITE_SECENEKLERI = [
        ('1', '1'),
        ('2', '2')
    ]

    mamul_model = models.CharField(max_length=32, choices=MAMUL_SECENEKLERI)
    kalite = models.CharField(
        max_length=1, choices=KALITE_SECENEKLERI, default='1')
    koli_turu = models.CharField(max_length=8)
    koli_adet = models.IntegerField()
    kolideki_mamul_adet = models.PositiveIntegerField()
    imalat = models.BooleanField(default=True)
    notlar = models.CharField(max_length=256, blank=True)
    tarih = models.DateTimeField(auto_now_add=True)
    kullanici = models.ForeignKey(User, on_delete=models.PROTECT)

    def save(self, *args, **kwargs):
        if self.koli_adet != 0:
            super(KoliDegisiklik, self).save(*args, **kwargs)

# Hammaddeler:


class HammaddeSonDurum(models.Model):
    tarih = models.DateField(unique=True)
    AmonyumBikarbonat = models.PositiveIntegerField(default=0)
    BoyaSokucuSolvent = models.PositiveIntegerField(default=0)
    CigBezirYagi = models.PositiveIntegerField(default=0)
    CinkoStarat = models.PositiveIntegerField(default=0)
    DPG = models.PositiveIntegerField(default=0)
    Hexa80 = models.PositiveIntegerField(default=0)
    Merkapto = models.PositiveIntegerField(default=0)
    Mikrotem = models.PositiveIntegerField(default=0)
    NeozaponBlack = models.PositiveIntegerField(default=0)
    NigroSine = models.PositiveIntegerField(default=0)
    SentetikDemiroksitBoya = models.PositiveIntegerField(default=0)
    SodyumHidroksit = models.PositiveIntegerField(default=0)
    TitanDioksit = models.PositiveIntegerField(default=0)
    Toluol = models.PositiveIntegerField(default=0)
    ZMBT = models.PositiveIntegerField(default=0)
    CamTozu = models.PositiveIntegerField(default=0)
    EtilGlikol = models.PositiveIntegerField(default=0)
    GrafikTozu = models.PositiveIntegerField(default=0)
    KalafonRecine = models.PositiveIntegerField(default=0)
    Kukurt = models.PositiveIntegerField(default=0)
    TriklorEtilen = models.PositiveIntegerField(default=0)
    DM = models.PositiveIntegerField(default=0)
    Derkompleks = models.PositiveIntegerField(default=0)
    Heptan = models.PositiveIntegerField(default=0)
    PismisBezirYagi = models.PositiveIntegerField(default=0)
    PVI = models.PositiveIntegerField(default=0)
    SulegenBoya = models.PositiveIntegerField(default=0)
    Whitesprit = models.PositiveIntegerField(default=0)
    AgizBandi = models.PositiveIntegerField(default=0)
    BaskisizKoli = models.PositiveIntegerField(default=0)
    DerbyCelikBurunluCizmeKutusu = models.PositiveIntegerField(default=0)
    DerbyFiletBezliKolisi = models.PositiveIntegerField(default=0)
    DerbyMerdaneBezliKolisi = models.PositiveIntegerField(default=0)
    DerbyMerdaneFanilaliKolisi = models.PositiveIntegerField(default=0)
    GislavedMerdaneIskarpinKolisi = models.PositiveIntegerField(default=0)
    GislavedZenneIskarpinKolisi = models.PositiveIntegerField(default=0)
    HutbakKagidi = models.PositiveIntegerField(default=0)
    KeseKagidi = models.PositiveIntegerField(default=0)
    KobaltElektrikciKaucukCizmeKolisi = models.PositiveIntegerField(default=0)
    KobaltKaucukCizmeKolisi = models.PositiveIntegerField(default=0)
    KrepCizmeUzunKoncKolisi = models.PositiveIntegerField(default=0)
    PlastikCember = models.PositiveIntegerField(default=0)
    DerbyBotKolisi = models.PositiveIntegerField(default=0)
    DerbyKrepKaucukCizmeKolisi = models.PositiveIntegerField(default=0)
    DerbyZenneBezliKolisi = models.PositiveIntegerField(default=0)
    KobaltKaucukDayanikliCizmeKutusu = models.PositiveIntegerField(default=0)
    KoliBandi = models.PositiveIntegerField(default=0)
    KrepBotKolisi = models.PositiveIntegerField(default=0)
    NaylonTorbaBot = models.PositiveIntegerField(default=0)
    DerbyBotKutusu = models.PositiveIntegerField(default=0)
    DerbyKrepKaucukCizmeKutusu = models.PositiveIntegerField(default=0)
    KobaltKaucukElektrikciCizmeKutusu = models.PositiveIntegerField(default=0)
    KobaltCizmeEtiketi = models.PositiveIntegerField(default=0)
    KrepCizmeKisaKoncKolisi = models.PositiveIntegerField(default=0)
    NaylonTorbaCizme = models.PositiveIntegerField(default=0)
    KrepYuzHamur = models.PositiveIntegerField(default=0)
    KrepTabanHamur = models.PositiveIntegerField(default=0)
    VardolaHamur = models.PositiveIntegerField(default=0)
    KrepFoderHamur = models.PositiveIntegerField(default=0)
    GalosYuzHamur = models.PositiveIntegerField(default=0)
    GalosTabanHamur = models.PositiveIntegerField(default=0)
    GalosFoderHamur = models.PositiveIntegerField(default=0)
    RejenereHamur = models.PositiveIntegerField(default=0)
    KahverengiYuzHamur = models.PositiveIntegerField(default=0)
    CelikBurunluTabanHamur = models.PositiveIntegerField(default=0)
    KobaltElektrikciYuzHamur = models.PositiveIntegerField(default=0)
    KobaltElektrikciTabanHamur = models.PositiveIntegerField(default=0)
    KobaltSiyahYuzHamur = models.PositiveIntegerField(default=0)
    KobaltSiyahTabanHamur = models.PositiveIntegerField(default=0)
    KobaltYesilYuzHamur = models.PositiveIntegerField(default=0)
    KobaltYesilTabanHamur = models.PositiveIntegerField(default=0)
    Kevlar = models.PositiveIntegerField(default=0)
    Eva = models.PositiveIntegerField(default=0)
    KompozitBurun = models.PositiveIntegerField(default=0)
    CizmeCorabi = models.PositiveIntegerField(default=0)
    OverlokIpi = models.PositiveIntegerField(default=0)
    PresKesimTakozu = models.PositiveIntegerField(default=0)
    AyakkabiTabanKecesi = models.PositiveIntegerField(default=0)
    CelikBurun = models.PositiveIntegerField(default=0)
    Fermuar = models.PositiveIntegerField(default=0)
    MaskelemeBandi = models.PositiveIntegerField(default=0)
    GalosKahveTabanAstariBez = models.PositiveIntegerField(default=0)
    KrepBeyazBez = models.PositiveIntegerField(default=0)
    KrepTabanAstariBez = models.PositiveIntegerField(default=0)
    GalosDeveTuyuTabanAstariBez = models.PositiveIntegerField(default=0)
    GalosPembeBez = models.PositiveIntegerField(default=0)
    GalosFordBezi = models.PositiveIntegerField(default=0)
    GalosPembeTabanAstariBez = models.PositiveIntegerField(default=0)
    KrepAntistatikTabanAstariBez = models.PositiveIntegerField(default=0)
    AntiSkalant = models.PositiveIntegerField(default=0)
    KazanTuzu = models.PositiveIntegerField(default=0)
    GalosKahveBez = models.PositiveIntegerField(default=0)
    GalosDeveTuyuBez = models.PositiveIntegerField(default=0)


class HammaddeDegisiklik(models.Model):
    HAMMADDE_SECENEKLERI = [
        ('Kimyasallar', (
            ('AmonyumBikarbonat', 'Amonyum Bikarbonat'),
            ('BoyaSokucuSolvent', 'Boya Sökücü Solvent'),
            ('CigBezirYagi', 'Çiğ Bezir Yağı'),
            ('CinkoStarat', 'Çinko Starat'),
            ('DPG', 'DPG'),
            ('Hexa80', 'Hexa80'),
            ('Merkapto', 'Merkapto'),
            ('Mikrotem', 'Mikrotem'),

dashboard/models.py
import os

from django import forms
from django.contrib.auth.models import User
from django.core.files.images import get_image_dimensions
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from api.models import MyModelForm


def avatar_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/avatar/user_<username>.<file_extension>
    filename, file_extension = os.path.splitext(filename)
    return 'avatar/user_{0}{1}'.format(instance.user.username, file_extension)

# from: https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    photo = models.ImageField(upload_to=avatar_path, blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class AccountFormU(MyModelForm):
    class Meta:
        model = User
        fields = ('first_name','last_name',)

class AccountFormP(MyModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)
        labels = {
            'title': 'Ünvan',
            'photo': 'Fotoğraf',
        }

dashboard/templates/dashboard/koli/kolieklecikar.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load dashboard_filters %}
{% block title %}Koli Ekle/Çıkar{% endblock %}
{% block icon %}pe-7s-box2 icon-gradient bg-happy-itmeo{% endblock %}
{% block pagetitle %}Koli Ekle/Çıkar{% endblock %}
{% block pagesubtitle %}Bu sayfadan stok içeriğine koli eklemesi ve çıkarması yapılır. {% endblock %}
{% block extracss %}
<link rel="stylesheet" href="{% static 'dashboard/chosen.css' %}">
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12 col-lg-6">
        <div class="mb-3 card">
            <div class="card-body">
                <h5 class="card-title">Koli Ekle / Çıkar</h5>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-lg">Kaydet</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-12 col-lg-6">
        <div class="mb-3 card">
            <div class="card-body">
                <h5 class="card-title">Son 10 Koli Girdi / Çıktı İşlemi</h5>
                <div class="scroll-area-lg">
                    <div class="scrollbar-container">
                        <ul class="rm-list-borders rm-list-borders-scroll list-group list-group-flush">
                        {% for row in son_on %}
                            <li class="list-group-item">
                                <div class="widget-content p-0">
                                    <div class="widget-content-wrapper">
                                        <div class="widget-content-left mr-3">
                                        {% if row.kullanici.profile.photo %}
                                            <img width="42" class="rounded-circle" src="/uploadedmedia/{{ row.kullanici.profile.photo }}" alt="">
                                        {% else %}
                                            <img width="42" class="rounded-circle" src="{% static 'dashboard/images/avatars/default_avatar.png' %}" alt="">
                                        {% endif %}
                                        </div>
                                        <div class="widget-content-left">
                                            <div class="widget-heading">{{ row.kullanici.get_full_name }}</div>
                                            <div class="widget-subheading">{{ row.kullanici.profile.title }}</div>
                                        </div>
                                        <div class="widget-content-right" data-toggle="tooltip" data-placement="bottom" data-original-title="Tarih: {{ row.tarih }}">
                                            <div class="font-size-xlg text-muted">
                                                <small class="pr-1">{{ row.get_mamul_model_display }}({{ row.koli_turu }})</small>
                                                <span>{{ row.koli_adet|abs }}</span>
                                                <small class="text-{% if row.koli_adet < 0 %}danger{% else %}success{% endif %} pl-2">
                                                    <i class="fa fa-angle-{% if row.koli_adet < 0 %}down{% else %}up{% endif %}"></i>
                                                </small>
                                            </div>
                                        </div>
                                        <button class="ml-2 btn btn-danger" onclick="window.location.href = '{% url "dashboard:kolieklecikar_sil" row.id %}';"><i class="pe-7s-trash"></i></button>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extrascript %}
<script src="{% static 'dashboard/scripts/chosen.jquery.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/scripts/chosen.init.js' %}" type="text/javascript"></script>
<script type="text/javascript">
$('#id_mamul_model').change(function ()
{
switch($('#id_mamul_model :selected').parent().attr('label')) {
    case 'Krep Çizme':
        $('#id_kolideki_mamul_adet').val(20);
        break;
    case 'Galoş Ayakkabı':
        $('#id_kolideki_mamul_adet').val(50);
        break;
    case 'Kobalt Çizme':
        $('#id_kolideki_mamul_adet').val(10);
        break;
    default:
        $('#id_kolideki_mamul_adet').val(null);
}
});
</script>
{% endblock %}

dashboard/templates/dashboard/koli/kolieklecikar_sil.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load dashboard_filters %}
{% block title %}Koli İşlemi Sil{% endblock %}
{% block icon %}pe-7s-trash icon-gradient bg-love-kiss{% endblock %}
{% block pagetitle %}Koli İşlemi Sil{% endblock %}
{% block pagesubtitle %}Bu sayfadan daha önce girilmiş <a href="{% url 'dashboard:kolieklecikar' %}">Koli Ekle / Çıkar</a> işlemi silinir. Bugün içinde yapılmamış işlemleri silemezsiniz.<br />UYARI: Koli model sisteminin çok karmaşık olmasından kaynaklı, bu kayıtları en son yapılan değişiklikten başlayarak silmeniz gerekmektedir.{% endblock %}
{% block content %}
<div class="card mb-3 widget-content">
    <div class="card-body">
        <h5 class="card-title">Bu Koli Ekle / Çıkar İşlemini Sil</h5>
        <div class="widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading">{{ record.get_mamul_model_display }}</div>
                        <div class="widget-subheading">Model</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading">{{ record.kalite }}</div>
                        <div class="widget-subheading">Kalite</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading">{{ record.koli_turu }}</div>
                        <div class="widget-subheading">Numara</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading">{{ record.koli_adet }}</div>
                        <div class="widget-subheading">Koli Adedi</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading">{{ record.kolideki_mamul_adet }}</div>
                        <div class="widget-subheading">Kolideki Mamul Sayısı</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading">{{ record.imalat|bool_to_turkish }}</div>
                        <div class="widget-subheading">İmalat?</div>
                    </div>
                </div>
            </div>
        </div>
        {% if record.notlar %}
        <div class="widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading">{{ record.notlar }}</div>
                        <div class="widget-subheading">Notlar</div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading">{{ record.tarih }}</div>
                        <div class="widget-subheading">Tarih</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading">{{ record.kullanici.get_full_name }}</div>
                        <div class="widget-subheading">Değişikliği Yapan</div>
                    </div>
                </div>
            </div>
        </div>
        <form method="POST">
            <button class="btn btn-outline-focus ml-3 mr-2" onclick="window.location.href = '{% url "dashboard:kolieklecikar" %}';" type="button">&laquo; Geri Dön</button>
            {% csrf_token %}
            <button class="btn btn-danger" type="submit"><i class="pe-7s-trash"></i> Sil</button>
        </form>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/koli/kolirapor.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load dashboard_filters %}
{% block title %}Koli Rapor{% endblock %}
{% block icon %}pe-7s-box2 icon-gradient bg-happy-itmeo{% endblock %}
{% block pagetitle %}Koli Rapor{% endblock %}
{% block pagesubtitle %}Koli Rapor{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-6">
        <div class="main-card mb-3 card">
            <div class="card-body">
                <h5 class="card-title">Koli Giriş Çıkışları</h5>
                <table class="mb-0 table table-hover">
                    <thead>
                        <tr>
                            <th>Tarih</th>
                            <th>Model</th>
                            <th>Numara</th>
                            <th>Koli Adedi</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for degisiklik in koli_son_degisiklikler %}
                        <tr>
                            <th scope="row">{{ degisiklik.tarih|date:'j/n/Y G:i' }}</th>
                            <td>{{ degisiklik.get_mamul_model_display }}</td>
                            <td>{{ degisiklik.koli_turu }}</td>
                            <td>{{ degisiklik.koli_adet }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <a href="{% url 'dashboard:kolirapor' %}?istek=deg_tumu">Tümünü gör</a>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="main-card mb-3 card">
            <div class="card-body">
                <h5 class="card-title">Koli Stok Durumu</h5>
                <table class="mb-0 table table-hover">
                    <thead>
                        <tr>
                            <th>Modeller</th>
                            <th>Tarih: {{ durum.tarih|date:'j/n/Y' }}</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for field in durum.fields %}
                        <tr>
                            <th colspan="2" style="text-align:center;">{{ field.0 }}</th>
                        </tr>
                        {% for material in field.1 %}
                        <tr>
                            <th><a href="{% url 'dashboard:kolirapor_tek_detay' material.2 %}">{{ material.0 }}</a></th>
                            <td>{{ material.1|ksdpackonly }}</td>
                        </tr>
                    {% endfor %}{% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <a href="{% url 'dashboard:kolirapor' %}?istek=son_tumu">Geçmiş bir gün için stok durumu sorgula</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/koli/kolirapor_degtumu.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load dashboard_filters %}
{% block title %}Koli Rapor{% endblock %}
{% block icon %}pe-7s-box2 icon-gradient bg-happy-itmeo{% endblock %}
{% block pagetitle %}Koli Rapor{% endblock %}
{% block pagesubtitle %}Koli Rapor{% endblock %}
{% block content %}
<div class="main-card mb-3 card">
    <div class="card-body">
        <h5 class="card-title">Tüm Koli Giriş Çıkışları</h5>
        <table class="mb-0 table table-hover">
            <thead>
                <tr>
                    <th>Tarih</th>
                    <th>Model</th>
                    <th>Kalite</th>
                    <th>Numara</th>
                    <th>Koli Adedi</th>
                    <th>Çift Adedi</th>
                    <th>İmalat/Satış mı?</th>
                    <th>Notlar</th>
                    <th>Değişikliği Yapan</th>
                </tr>
            </thead>
            <tbody>
            {% for degisiklik in data %}
                <tr>
                    <th scope="row">{{ degisiklik.tarih|date:'j/n/Y G:i' }}</th>
                    <td>{{ degisiklik.get_mamul_model_display }}</td>
                    <td>{{ degisiklik.kalite }}</td>
                    <td>{{ degisiklik.koli_turu }}</td>
                    <td>{{ degisiklik.koli_adet }}</td>
                    <td>{{ degisiklik.koli_adet|times:degisiklik.kolideki_mamul_adet }}</td>
                    <td>{{ degisiklik.imalat|bool_to_turkish }}</td>
                    <td>{% if degisiklik.notlar %}
                        <div class="widget-content-right" data-toggle="tooltip" data-placement="bottom" data-original-title="{{ degisiklik.notlar }}">
                        {{ degisiklik.notlar|truncatechars:10 }}
                        </div>{% endif %}
                    </td>
                    <td>{{ degisiklik.kullanici.get_full_name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}