api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

# urlpatterns = [
    # path('ayakkabi/', views.AyakkabiList.as_view()),
    # path('ayakkabi/<int:pk>/', views.AyakkabiDetail.as_view()),
# ]

# urlpatterns = format_suffix_patterns(urlpatterns)

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.anasayfa, name='anasayfa'),
    path('arama/', views.arama, name='arama'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('lisans/', views.lisans, name='lisans'),
    path('hesap/', views.hesap, name='hesap'),
    path('sifredegistir/', views.sifredegistir, name='sifredegistir'),
    path('koli/eklecikar/', views.kolieklecikar, name='kolieklecikar'),
    path('koli/sil/<int:pk>/', views.kolieklecikar_sil, name='kolieklecikar_sil'),
    path('koli/', views.kolirapor, name='kolirapor'),
    path('koli/guncelle/', views.koliguncelle, name='koliguncelle'),
    path('koli/detay/<str:urun>', views.kolirapor_tek_detay, name='kolirapor_tek_detay'),
    path('hammadde/eklecikar/', views.hammaddeeklecikar, name='hammaddeeklecikar'),
    path('hammadde/sil/<int:pk>/', views.hammaddeeklecikar_sil, name='hammaddeeklecikar_sil'),
    path('hammadde/', views.hammadderapor, name='hammadderapor'),
    path('hammadde/guncelle/', views.hammaddeguncelle, name='hammaddeguncelle'),
    path('yasak/', views.yasak, name='yasak'),
]

tsp_prj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('', include('dashboard.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='dashboard/login.html')),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
]

api/models.py
import pickle

from django import forms
from django.contrib.auth.models import User
from django.db import IntegrityError, models
from django.dispatch import receiver
from django.utils import timezone

from dashboard.methodpack import sorting_key, validate_package_type

# Mamuller:


class KoliSonDurum(models.Model):
    tarih = models.DateField(unique=True)
    KrepKisaKonc = models.BinaryField(blank=True, editable=True)
    KrepUzunKonc = models.BinaryField(blank=True, editable=True)
    KrepGarsonKisa = models.BinaryField(blank=True, editable=True)
    KrepGarsonUzun = models.BinaryField(blank=True, editable=True)
    KrepKahveBot = models.BinaryField(blank=True, editable=True)
    KrepSiyahBot = models.BinaryField(blank=True, editable=True)
    KrepCelikBurunluCizme = models.BinaryField(blank=True, editable=True)
    KasikCizme = models.BinaryField(blank=True, editable=True)
    FiletBezli = models.BinaryField(blank=True, editable=True)
    ZenneBezli = models.BinaryField(blank=True, editable=True)
    MerdaneBezli = models.BinaryField(blank=True, editable=True)
    MerdaneFanilali = models.BinaryField(blank=True, editable=True)
    ZenneIskarpin = models.BinaryField(blank=True, editable=True)
    MerdaneIskarpin = models.BinaryField(blank=True, editable=True)
    GarsonIskarpin = models.BinaryField(blank=True, editable=True)
    PresCizmeOB = models.BinaryField(blank=True, editable=True)
    PresCizmeS4 = models.BinaryField(blank=True, editable=True)
    PresCizmeS5 = models.BinaryField(blank=True, editable=True)
    ElektrikciOB = models.BinaryField(blank=True, editable=True)
    ElektrikciS4 = models.BinaryField(blank=True, editable=True)
    ElektrikciS5 = models.BinaryField(blank=True, editable=True)


class KoliDegisiklik(models.Model):
    MAMUL_SECENEKLERI = [
        ('Krep Çizme', (
            ('KrepKisaKonc', 'Krep Kısa Konç'),
            ('KrepUzunKonc', 'Krep Uzun Konç'),
            ('KrepGarsonKisa', 'Krep Garson Kısa'),
            ('KrepGarsonUzun', 'Krep Garson Uzun'),
            ('KrepKahveBot', 'Krep Kahve Bot'),
            ('KrepSiyahBot', 'Krep Siyah Bot'),
            ('KrepCelikBurunluCizme', 'Krep Çelik Burunlu Çizme'),
            ('KasikCizme', 'Kasık Çizme'),
        )
        ),
        ('Galoş Ayakkabı', (
            ('FiletBezli', 'Filet Bezli'),
            ('ZenneBezli', 'Zenne Bezli'),
            ('MerdaneBezli', 'Merdane Bezli'),
            ('MerdaneFanilali', 'Merdane Fanilalı'),
            ('ZenneIskarpin', 'Zenne İskarpin'),
            ('MerdaneIskarpin', 'Merdane İskarpin'),
            ('GarsonIskarpin', 'Garson İskarpin'),
        )
        ),
        ('Kobalt Çizme', (
            ('PresCizmeOB', 'Pres Çizme OB'),
            ('PresCizmeS4', 'Pres Çizme S4'),
            ('PresCizmeS5', 'Pres Çizme S5'),
            ('ElektrikciOB', 'Elektrikçi OB'),
            ('ElektrikciS4', 'Elektrikçi S4'),
            ('ElektrikciS5', 'Elektrikçi S5'),
        )
        ),
    ]

    KALITE_SECENEKLERI = [
        ('1', '1'),
        ('2', '2')
    ]

    mamul_model = models.CharField(max_length=32, choices=MAMUL_SECENEKLERI)
    kalite = models.CharField(
        max_length=1, choices=KALITE_SECENEKLERI, default='1')
    koli_turu = models.CharField(max_length=8)
    koli_adet = models.IntegerField()
    kolideki_mamul_adet = models.PositiveIntegerField()
    imalat = models.BooleanField(default=True)
    notlar = models.CharField(max_length=256, blank=True)
    tarih = models.DateTimeField(auto_now_add=True)
    kullanici = models.ForeignKey(User, on_delete=models.PROTECT)

    def save(self, *args, **kwargs):
        if self.koli_adet != 0:
            super(KoliDegisiklik, self).save(*args, **kwargs)

# Hammaddeler:


class HammaddeSonDurum(models.Model):
    tarih = models.DateField(unique=True)
    AmonyumBikarbonat = models.PositiveIntegerField(default=0)
    BoyaSokucuSolvent = models.PositiveIntegerField(default=0)
    CigBezirYagi = models.PositiveIntegerField(default=0)
    CinkoStarat = models.PositiveIntegerField(default=0)
    DPG = models.PositiveIntegerField(default=0)
    Hexa80 = models.PositiveIntegerField(default=0)
    Merkapto = models.PositiveIntegerField(default=0)
    Mikrotem = models.PositiveIntegerField(default=0)
    NeozaponBlack = models.PositiveIntegerField(default=0)
    NigroSine = models.PositiveIntegerField(default=0)
    SentetikDemiroksitBoya = models.PositiveIntegerField(default=0)
    SodyumHidroksit = models.PositiveIntegerField(default=0)
    TitanDioksit = models.PositiveIntegerField(default=0)
    Toluol = models.PositiveIntegerField(default=0)
    ZMBT = models.PositiveIntegerField(default=0)
    CamTozu = models.PositiveIntegerField(default=0)
    EtilGlikol = models.PositiveIntegerField(default=0)
    GrafikTozu = models.PositiveIntegerField(default=0)
    KalafonRecine = models.PositiveIntegerField(default=0)
    Kukurt = models.PositiveIntegerField(default=0)
    TriklorEtilen = models.PositiveIntegerField(default=0)
    DM = models.PositiveIntegerField(default=0)
    Derkompleks = models.PositiveIntegerField(default=0)
    Heptan = models.PositiveIntegerField(default=0)
    PismisBezirYagi = models.PositiveIntegerField(default=0)
    PVI = models.PositiveIntegerField(default=0)
    SulegenBoya = models.PositiveIntegerField(default=0)
    Whitesprit = models.PositiveIntegerField(default=0)
    AgizBandi = models.PositiveIntegerField(default=0)
    BaskisizKoli = models.PositiveIntegerField(default=0)
    DerbyCelikBurunluCizmeKutusu = models.PositiveIntegerField(default=0)
    DerbyFiletBezliKolisi = models.PositiveIntegerField(default=0)
    DerbyMerdaneBezliKolisi = models.PositiveIntegerField(default=0)
    DerbyMerdaneFanilaliKolisi = models.PositiveIntegerField(default=0)
    GislavedMerdaneIskarpinKolisi = models.PositiveIntegerField(default=0)
    GislavedZenneIskarpinKolisi = models.PositiveIntegerField(default=0)
    HutbakKagidi = models.PositiveIntegerField(default=0)
    KeseKagidi = models.PositiveIntegerField(default=0)
    KobaltElektrikciKaucukCizmeKolisi = models.PositiveIntegerField(default=0)
    KobaltKaucukCizmeKolisi = models.PositiveIntegerField(default=0)
    KrepCizmeUzunKoncKolisi = models.PositiveIntegerField(default=0)
    PlastikCember = models.PositiveIntegerField(default=0)
    DerbyBotKolisi = models.PositiveIntegerField(default=0)
    DerbyKrepKaucukCizmeKolisi = models.PositiveIntegerField(default=0)
    DerbyZenneBezliKolisi = models.PositiveIntegerField(default=0)
    KobaltKaucukDayanikliCizmeKutusu = models.PositiveIntegerField(default=0)
    KoliBandi = models.PositiveIntegerField(default=0)
    KrepBotKolisi = models.PositiveIntegerField(default=0)
    NaylonTorbaBot = models.PositiveIntegerField(default=0)
    DerbyBotKutusu = models.PositiveIntegerField(default=0)
    DerbyKrepKaucukCizmeKutusu = models.PositiveIntegerField(default=0)
    KobaltKaucukElektrikciCizmeKutusu = models.PositiveIntegerField(default=0)
    KobaltCizmeEtiketi = models.PositiveIntegerField(default=0)
    KrepCizmeKisaKoncKolisi = models.PositiveIntegerField(default=0)
    NaylonTorbaCizme = models.PositiveIntegerField(default=0)
    KrepYuzHamur = models.PositiveIntegerField(default=0)
    KrepTabanHamur = models.PositiveIntegerField(default=0)
    VardolaHamur = models.PositiveIntegerField(default=0)
    KrepFoderHamur = models.PositiveIntegerField(default=0)
    GalosYuzHamur = models.PositiveIntegerField(default=0)
    GalosTabanHamur = models.PositiveIntegerField(default=0)
    GalosFoderHamur = models.PositiveIntegerField(default=0)
    RejenereHamur = models.PositiveIntegerField(default=0)
    KahverengiYuzHamur = models.PositiveIntegerField(default=0)
    CelikBurunluTabanHamur = models.PositiveIntegerField(default=0)
    KobaltElektrikciYuzHamur = models.PositiveIntegerField(default=0)
    KobaltElektrikciTabanHamur = models.PositiveIntegerField(default=0)
    KobaltSiyahYuzHamur = models.PositiveIntegerField(default=0)
    KobaltSiyahTabanHamur = models.PositiveIntegerField(default=0)
    KobaltYesilYuzHamur = models.PositiveIntegerField(default=0)
    KobaltYesilTabanHamur = models.PositiveIntegerField(default=0)
    Kevlar = models.PositiveIntegerField(default=0)
    Eva = models.PositiveIntegerField(default=0)
    KompozitBurun = models.PositiveIntegerField(default=0)
    CizmeCorabi = models.PositiveIntegerField(default=0)
    OverlokIpi = models.PositiveIntegerField(default=0)
    PresKesimTakozu = models.PositiveIntegerField(default=0)
    AyakkabiTabanKecesi = models.PositiveIntegerField(default=0)
    CelikBurun = models.PositiveIntegerField(default=0)
    Fermuar = models.PositiveIntegerField(default=0)
    MaskelemeBandi = models.PositiveIntegerField(default=0)
    GalosKahveTabanAstariBez = models.PositiveIntegerField(default=0)
    KrepBeyazBez = models.PositiveIntegerField(default=0)
    KrepTabanAstariBez = models.PositiveIntegerField(default=0)
    GalosDeveTuyuTabanAstariBez = models.PositiveIntegerField(default=0)
    GalosPembeBez = models.PositiveIntegerField(default=0)
    GalosFordBezi = models.PositiveIntegerField(default=0)
    GalosPembeTabanAstariBez = models.PositiveIntegerField(default=0)
    KrepAntistatikTabanAstariBez = models.PositiveIntegerField(default=0)
    AntiSkalant = models.PositiveIntegerField(default=0)
    KazanTuzu = models.PositiveIntegerField(default=0)
    GalosKahveBez = models.PositiveIntegerField(default=0)
    GalosDeveTuyuBez = models.PositiveIntegerField(default=0)


class HammaddeDegisiklik(models.Model):
    HAMMADDE_SECENEKLERI = [
        ('Kimyasallar', (
            ('AmonyumBikarbonat', 'Amonyum Bikarbonat'),
            ('BoyaSokucuSolvent', 'Boya Sökücü Solvent'),
            ('CigBezirYagi', 'Çiğ Bezir Yağı'),
            ('CinkoStarat', 'Çinko Starat'),
            ('DPG', 'DPG'),
            ('Hexa80', 'Hexa80'),
            ('Merkapto', 'Merkapto'),
            ('Mikrotem', 'Mikrotem'),

dashboard/models.py
import os

from django import forms
from django.contrib.auth.models import User
from django.core.files.images import get_image_dimensions
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from api.models import MyModelForm


def avatar_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/avatar/user_<username>.<file_extension>
    filename, file_extension = os.path.splitext(filename)
    return 'avatar/user_{0}{1}'.format(instance.user.username, file_extension)

# from: https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    photo = models.ImageField(upload_to=avatar_path, blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class AccountFormU(MyModelForm):
    class Meta:
        model = User
        fields = ('first_name','last_name',)

class AccountFormP(MyModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)
        labels = {
            'title': 'Ünvan',
            'photo': 'Fotoğraf',
        }

dashboard/templates/dashboard/anasayfa.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load dashboard_filters %}
{% block title %}{{ title }}{% endblock %}
{% block icon %}pe-7s-monitor icon-gradient bg-mean-fruit{% endblock %}
{% block pagetitle %}{{ title }}{% endblock %}
{% block pagesubtitle %}Anasayfa{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-xl-4">
        <div class="card mb-3 widget-content bg-midnight-bloom">
            <div class="widget-content-wrapper text-white">
                <div class="widget-content-left">
                    <div class="widget-heading">Aylık Üretim</div>
                    <div class="widget-subheading">Geçen ay üretilen toplam ayakkabı</div>
                </div>
                {% with uretim=cizgi_grafik_veri.1|last %}
                <div class="widget-content-right" data-toggle="tooltip" data-placement="bottom" data-original-title="{{ uretim }}">
                    <div class="widget-numbers text-white"><span>{{ uretim|humanize_int }}</span></div>
                </div>
                {% endwith %}
            </div>
        </div>
    </div>
    <div class="col-md-6 col-xl-4">
        <div class="card mb-3 widget-content bg-arielle-smile">
            <div class="widget-content-wrapper text-white">
                <div class="widget-content-left">
                    <div class="widget-heading">Birinci Kalite Yüzdesi</div>
                    <div class="widget-subheading">Birinci / ikinci kalite oranı</div>
                </div>
                <div class="widget-content-right">
                    <div class="widget-numbers text-white"><span>%{{ birinci_kalite_oran }}</span></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-xl-4">
        <div class="card mb-3 widget-content bg-grow-early">
            <div class="widget-content-wrapper text-white">
                <div class="widget-content-left">
                    <div class="widget-heading">Aylık Satış</div>
                    <div class="widget-subheading">Geçen ay satılan toplam ayakkabı</div>
                </div>
                {% with satis=cizgi_grafik_veri.2|last %}
                <div class="widget-content-right" data-toggle="tooltip" data-placement="bottom" data-original-title="{{ satis }}">
                    <div class="widget-numbers text-white"><span>{{ satis|humanize_int }}</span></div>
                </div>
                {% endwith %}
            </div>
        </div>
    </div>
    <div class="d-xl-none d-lg-block col-md-6 col-xl-4">
        <div class="card mb-3 widget-content bg-premium-dark">
            <div class="widget-content-wrapper text-white">
                <div class="widget-content-left">
                    <div class="widget-heading">Toplam Koli</div>
                    <div class="widget-subheading">Stoktaki toplam koli sayısı</div>
                </div>
                <div class="widget-content-right" data-toggle="tooltip" data-placement="bottom" data-original-title="{{ toplam_koli }}">
                    <div class="widget-numbers text-warning"><span>{{ toplam_koli|humanize_int }}</span></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-6">
        <div class="mb-3 card">
            <div class="card-header-tab card-header-tab-animation card-header">
                <div class="card-header-title">
                    <i class="header-icon lnr-apartment icon-gradient bg-love-kiss"> </i>
                    Aylık Üretim
                </div>
            </div>
            <div class="card-body">
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="tabs-eg-77">
                        <div class="card mb-3 widget-chart widget-chart2 text-left w-100">
                            <div class="widget-chat-wrapper-outer">
                                <div class="widget-chart-wrapper widget-chart-wrapper-lg opacity-10 m-0">
                                    <div style="height: 350px;">
                                        <canvas id="aylik-uretim-grafik"></canvas>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <h6 class="text-muted text-uppercase font-size-md opacity-5 font-weight-normal">
                            Son Değişiklikler</h6>
                        <div class="scroll-area-sm">
                            <div class="scrollbar-container">
                                <ul class="rm-list-borders rm-list-borders-scroll list-group list-group-flush">
                                {% for row in son_bes %}
                                    <li class="list-group-item">
                                        <div class="widget-content p-0">
                                            <div class="widget-content-wrapper">
                                                <div class="widget-content-left mr-3">
                                                {% if row.kullanici.profile.photo %}
                                                    <img width="42" class="rounded-circle" src="/uploadedmedia/{{ row.kullanici.profile.photo }}" alt="">
                                                {% else %}
                                                    <img width="42" class="rounded-circle" src="{% static 'dashboard/images/avatars/default_avatar.png' %}" alt="">
                                                {% endif %}
                                                </div>
                                                <div class="widget-content-left">
                                                    <div class="widget-heading">{{ row.kullanici.get_full_name }}</div>
                                                    <div class="widget-subheading">{{ row.kullanici.profile.title }}</div>
                                                </div>
                                                <div class="widget-content-right" data-toggle="tooltip" data-placement="bottom" data-original-title="Tarih: {{ row.tarih }}">
                                                    <div class="font-size-xlg text-muted">
                                                        <small class="pr-1">{{ row.get_mamul_model_display }}({{ row.koli_turu }})</small>
                                                        <span>{{ row.koli_adet|abs }}</span>
                                                        <small class="text-{% if row.koli_adet < 0 %}danger{% else %}success{% endif %} pl-2">
                                                            <i class="fa fa-angle-{% if row.koli_adet < 0 %}down{% else %}up{% endif %}"></i>
                                                        </small>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12 col-lg-6">
        <div class="mb-3 card">
            <div class="card-header-tab card-header">
                <div class="card-header-title">
                    <i class="header-icon lnr-rocket icon-gradient bg-tempting-azure"> </i>
                    Birinci Sınıf Yüzdesi
                </div>
            </div>
            <div class="tab-content">
                <div class="tab-pane fade active show" id="tab-eg-55">
                    <div class="widget-chart p-3">
                        <canvas id="pasta-grafik"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extrascript %}
<script type="text/javascript">
var aylik_uretim_config = {
    type: 'line',
    data: {
        labels: {{ cizgi_grafik_veri.0|safe }},
        datasets: [{
            label: 'Üretim',
            backgroundColor: window.chartColors.green,
            borderColor: window.chartColors.green,
            data: {{ cizgi_grafik_veri.1 }},
            fill: false,
        }, {
            label: 'Satış',
            fill: false,
            backgroundColor: window.chartColors.blue,
            borderColor: window.chartColors.blue,
            data: {{ cizgi_grafik_veri.2 }},
        }]
    },
    options: {
        responsive: true,
        maintainAspectRatio: false,
        title: {
            display: true,
            text: 'Aylık Üretim ve Satış'
        },
        tooltips: {
            mode: 'index',
            intersect: false,
        },
        hover: {
            mode: 'nearest',
            intersect: true
        },
        scales: {
            xAxes: [{
                display: true,
                scaleLabel: {
                    display: true,
                    labelString: 'Aylar'
                }
            }],
            yAxes: [{
                display: true,
                scaleLabel: {
                    display: true,
                    labelString: 'Değerler'
                }
            }]
        }
    }
};

var pasta_config = {
            type: 'doughnut',
            data: {
                datasets: [{
                    data: [
                        {{ kalite1 }},
                        {{ kalite2 }},
                    ],
                    backgroundColor: [
                        window.chartColors.green,
                        window.chartColors.red,
                    ],
                    label: 'Kalite'
                }],
                labels: [
                    'Birinci Kalite',
                    'İkinci Kalite',
                ]
            },
            options: {
                responsive: true,
                legend: {
                    position: 'top',
                    display: ((screen.width < 450) ? false : true)
                },
                title: {
                    display: true,
                    text: 'Birinci / İkinci Kalite'
                },
                animation: {
                    animateScale: true,
                    animateRotate: true
                }
            }
        };

$(document).ready(function(event) {
            var aylik_uretim_ctx = document.getElementById('aylik-uretim-grafik').getContext('2d');
            window.cizgiGrafik = new Chart(aylik_uretim_ctx, aylik_uretim_config);
            var pasta_ctx = document.getElementById('pasta-grafik').getContext('2d');
            window.pastaGrafik = new Chart(pasta_ctx, pasta_config);
        });
</script>
{% endblock %}

dashboard/templates/dashboard/arama.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}Arama{% endblock %}
{% block icon %}pe-7s-search icon-gradient bg-night-fade{% endblock %}
{% block pagetitle %}Arama{% endblock %}
{% block pagesubtitle %}{% if q %}{{ q }} için arama sonuçları.{% else %}Arama değeri girmediniz.{% endif %}{% endblock %}
{% block content %}
<div class="main-card mb-3 card">
    <div class="card-body">
        <h5 class="card-title">Arama</h5>
        {% if q %}
        <span>{{ q }} arama değerine ait sonuç bulunamadı.</span>
        {% else %}
        <span>Lütfen bir arama değeri girin.</span>
        {% endif %}
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/blank.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load dashboard_filters %}
{% block title %}Boş Sayfa{% endblock %}
{% block icon %}pe-7s-paint-bucket icon-gradient bg-amy-crisp{% endblock %}
{% block pagetitle %}Boş Sayfa{% endblock %}
{% block pagesubtitle %}Boş Sayfa{% endblock %}
{% block content %}

{% endblock %}

dashboard/templates/dashboard/hesap.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}Hesap Ayarları{% endblock %}
{% block icon %}pe-7s-user icon-gradient bg-malibu-beach{% endblock %}
{% block extracss %}<link rel="stylesheet" type="text/css" href="{% static 'dashboard/croppie.css' %}" />{% endblock %}
{% block pagetitle %}Hesap Ayarları{% endblock %}
{% block pagesubtitle %}Bu sayfadan bazı hesap ayarlarınızı değiştirebilirsiniz. Değiştiremediğiniz alanları değiştirmek için lütfen <a href="{% url 'dashboard:iletisim' %}">sistem yöneticisiyle iletişime geçin.</a>{% endblock %}
{% block content %}
<div class="main-card mb-3 card">
    <div class="card-body">
        <h5 class="card-title">Hesap Ayarları</h5>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in formu %}
            <div class="position-relative row form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                <div class="col-sm-10">{{ field }}</div>
            </div>
            {% endfor %}
            {% for field in formp %}
            <div class="position-relative row form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                <div class="col-sm-10">{{ field.errors }}{{ field }}</div>
            </div>
            {% endfor %}
            <div id="croppieWrapper" class="d-none">
                <div id="croppieHere"></div>
            </div>
            <input type="hidden" name="croppieData" id="croppieData" value="">
            <div class="position-relative row form-check">
                <div class="col-sm-10 offset-sm-2">
                    <button type="submit" class="btn btn-primary">Kaydet</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block extrascript %}
    <script type="text/javascript" src="{% static 'dashboard/scripts/croppie.js' %}"></script>
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function() {
            var uploadCrop = new Croppie(document.getElementById('croppieHere'), {
                viewport: {
                    width: 128,
                    height: 128,
                    type: 'circle'
                },
                boundary: {
                    width: 200,
                    height: 200
                },
                showZoomer: false,
            });

            document.getElementById('croppieHere').addEventListener('update', function(ev) {
                document.getElementById('croppieData').value = ev.detail.points;
            });

            function readFile(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        uploadCrop.bind({
                            url: e.target.result
                        }).then(function(){
                            console.log('jQuery bind complete');
                        });
                    }
                    reader.readAsDataURL(input.files[0]);
                }
                else {
                    alert("Sorry - your browser doesn't support the FileReader API");
                }
            }

            document.getElementById('id_photo').addEventListener('change', function() {
                readFile(this);
                document.getElementById('croppieWrapper').className = "d-block";
            });
        });
    </script>
{% endblock %}

dashboard/templates/dashboard/yasak.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load dashboard_filters %}
{% block title %}Yasak{% endblock %}
{% block icon %}pe-7s-shield icon-gradient bg-love-kiss{% endblock %}
{% block pagetitle %}Yasak{% endblock %}
{% block pagesubtitle %}Bu sayfayı görme yetkiniz bulunmamaktadır.{% endblock %}
{% block content %}
<div class="mb-3 card card-body card-shadow-danger border border-danger" style="margin-left:150px;margin-right:150px;">
    <h5 class="card-title">Yasak</h5>
    <span style="margin:20px;">Bu sayfayı görme yetkiniz bulunmamaktadır.</span>
    <button class="btn btn-outline-focus" onclick="window.location.href = '{% url "dashboard:anasayfa" %}';">Anasayfaya Dön</button>
</div>
{% endblock %}