api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

# urlpatterns = [
    # path('ayakkabi/', views.AyakkabiList.as_view()),
    # path('ayakkabi/<int:pk>/', views.AyakkabiDetail.as_view()),
# ]

# urlpatterns = format_suffix_patterns(urlpatterns)

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.anasayfa, name='anasayfa'),
    path('arama/', views.arama, name='arama'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('lisans/', views.lisans, name='lisans'),
    path('hesap/', views.hesap, name='hesap'),
    path('sifredegistir/', views.sifredegistir, name='sifredegistir'),
    path('koli/eklecikar/', views.kolieklecikar, name='kolieklecikar'),
    path('koli/sil/<int:pk>/', views.kolieklecikar_sil, name='kolieklecikar_sil'),
    path('koli/', views.kolirapor, name='kolirapor'),
    path('koli/guncelle/', views.koliguncelle, name='koliguncelle'),
    path('koli/detay/<str:urun>', views.kolirapor_tek_detay, name='kolirapor_tek_detay'),
    path('hammadde/eklecikar/', views.hammaddeeklecikar, name='hammaddeeklecikar'),
    path('hammadde/sil/<int:pk>/', views.hammaddeeklecikar_sil, name='hammaddeeklecikar_sil'),
    path('hammadde/', views.hammadderapor, name='hammadderapor'),
    path('hammadde/guncelle/', views.hammaddeguncelle, name='hammaddeguncelle'),
    path('yasak/', views.yasak, name='yasak'),
]

tsp_prj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('', include('dashboard.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='dashboard/login.html')),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
]

dashboard/models.py
import os

from django import forms
from django.contrib.auth.models import User
from django.core.files.images import get_image_dimensions
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from api.models import MyModelForm


def avatar_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/avatar/user_<username>.<file_extension>
    filename, file_extension = os.path.splitext(filename)
    return 'avatar/user_{0}{1}'.format(instance.user.username, file_extension)

# from: https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    photo = models.ImageField(upload_to=avatar_path, blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class AccountFormU(MyModelForm):
    class Meta:
        model = User
        fields = ('first_name','last_name',)

class AccountFormP(MyModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)
        labels = {
            'title': 'Ünvan',
            'photo': 'Fotoğraf',
        }

dashboard/views.py
import os
import pickle

from django import forms
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import IntegrityError
from django.shortcuts import redirect, render
from django.utils import timezone

import api.models
import dashboard.methodpack as mp
import dashboard.serializers as s

from .decorators import group_required
from .models import AccountFormP, AccountFormU


# NoAuth sayfalar:
def iletisim(request):
    return render(request, 'dashboard/iletisim.html')


def lisans(request):
    licenses = ''
    with open(os.path.join(settings.BASE_DIR, 'dashboard', 'licenses'), 'r') as f:
        licenses = f.read().replace('\n', '<br />')
    return render(request, 'dashboard/lisans.html', {'licenses': licenses})

# Auth sayfalar:
@login_required
def anasayfa(request):
    data = {'title': 'Dashboard'}
    data['birinci_kalite_oran'], data['kalite1'], data['kalite2'], data['toplam_koli'] = mp.koli_son_durum_iterator(
        api.models.KoliSonDurum.objects.latest('tarih'))
    data['son_bes'] = api.models.KoliDegisiklik.objects.select_related(
        'kullanici__profile').order_by('-id')[:5]
    # TODO: Buraları veritabanına yazdır ay ay. Çok fazla gereksiz işlemci kullanımı var buralarda.
    aylar = ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara']
    tarih = timezone.localtime(timezone.now())
    data['cizgi_grafik_veri'] = [[], [], []]
    for i in range(6, 0, -1):
        ay = tarih.month-i
        yil = tarih.year
        if ay < 1:
            ay+=12
            yil-=1
        data['cizgi_grafik_veri'][0].append('{0}\'{1}'.format(aylar[ay-1], yil%100))
        uretim, satis = mp.monthly_production_and_sales(ay, yil)
        data['cizgi_grafik_veri'][1].append(uretim)
        data['cizgi_grafik_veri'][2].append(satis)
    return render(request, 'dashboard/anasayfa.html', data)


@login_required
def arama(request):
    q = ''
    if 'q' in request.GET.keys():
        q = request.GET['q']
    return render(request, 'dashboard/arama.html', {'q': q})


@login_required
def hesap(request):
    loggedin_user = User.objects.get(pk=request.user.id)
    if request.method == 'POST':
        formu = AccountFormU(request.POST, instance=loggedin_user)
        formp = AccountFormP(request.POST, request.FILES,
                             instance=loggedin_user.profile)
        if formu.is_valid() and formp.is_valid():
            formu.save()
            profile_obj = formp.save()
            if bool(formp.cleaned_data['photo']) and type(formp.cleaned_data['photo']) == InMemoryUploadedFile:
                # Yeni fotoğraf yüklenmiş demektir.
                # print(request.POST['croppieData'])
                croppieData = tuple(map(int, request.POST['croppieData'].split(',')))
                mp.profile_photo_resizer(profile_obj.photo.name, croppieData)
            messages.add_message(request, messages.SUCCESS,
                                 'Hesap bilgileriniz başarıyla kaydedilmiştir.')
            # from: https://groups.google.com/forum/#!topic/django-users/SLw6SrIC8wI
            return redirect('dashboard:anasayfa')
    elif request.method == 'GET':
        formu = AccountFormU(instance=loggedin_user)
        formp = AccountFormP(instance=loggedin_user.profile)
    return render(request, 'dashboard/hesap.html', {'formu': formu, 'formp': formp})


@login_required
def sifredegistir(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            # from: https://simpleisbetterthancomplex.com/tips/2016/08/04/django-tip-9-password-change-form.html
            update_session_auth_hash(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 'Şifreniz başarıyla değiştirilmiştir.')
            return redirect('dashboard:anasayfa')
    elif request.method == 'GET':
        form = PasswordChangeForm(request.user)
    return render(request, 'dashboard/sifredegistir.html', {'form': form})


@login_required
@group_required('editor')
def kolieklecikar(request):
    son_on = api.models.KoliDegisiklik.objects.select_related(
        'kullanici__profile').order_by('-id')[:10]
    if request.method == 'POST':
        form = api.models.KoliDegisiklikForm(request.POST)
        if form.is_valid():
            try:
                # from: https://stackoverflow.com/a/46941862
                #       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ THANK YOU SO MUCH!!!
                koli_degisiklik_obj = form.save(commit=False)
                koli_degisiklik_obj.kullanici_id = request.user.id
                koli_degisiklik_obj.save()
                messages.add_message(
                    request, messages.SUCCESS, 'Kayıt başarılı.')
                return redirect('dashboard:kolieklecikar')
            except IntegrityError:
                messages.add_message(
                    request, messages.ERROR, 'Veritabanına geçersiz girdi yapmaya çalıştınız. Stokta var olandan daha fazla malzemeyi çıktı gibi göstermeye çalışıyor olabilirsiniz. Girdiğiniz verileri gözden geçirin.')
    elif request.method == 'GET':
        form = api.models.KoliDegisiklikForm()
    return render(request, 'dashboard/koli/kolieklecikar.html', {'form': form, 'son_on': son_on})


@login_required
@group_required('editor')
def kolieklecikar_sil(request, pk):
    if request.method == 'POST':
        try:
            delet_dis = api.models.KoliDegisiklik.objects.get(pk=pk)
            delet_dis.delete()
            messages.add_message(
                request,
                messages.SUCCESS,
                'Silme işlemi başarılı.'
            )
        except IntegrityError:
            messages.add_message(
                request,
                messages.ERROR,
                'Kolideki değişiklikleri, kayıt sırasına göre, sondan başlayarak silmelisiniz. Ayrıca, başka gün içinde yapılan değişikliği silemezsiniz.'
            )
        return redirect('dashboard:kolieklecikar')
    elif request.method == 'GET':
        try:
            record = api.models.KoliDegisiklik.objects.get(pk=pk)
        except api.models.KoliDegisiklik.DoesNotExist:
            messages.add_message(request, messages.ERROR,
                                 'Böyle bir kayıt yok.')
            return redirect('dashboard:kolieklecikar')
        return render(request, 'dashboard/koli/kolieklecikar_sil.html', {'record': record})


@login_required
def kolirapor(request):
    if 'istek' in request.GET.keys():
        if request.GET['istek'] == 'deg_tumu':
            data = api.models.KoliDegisiklik.objects.select_related(
                'kullanici').order_by('-id')
            return render(request, 'dashboard/koli/kolirapor_degtumu.html', {'data': data})
        elif request.GET['istek'] == 'son_tumu':
            data = None
            if request.method == 'POST':
                form = api.models.GunGetirForm(request.POST)
                if form.is_valid():
                    try:
                        data = s.SingleRecordSerializer(
                            api.models.KoliSonDurum.objects.get(tarih=form.cleaned_data['gun']))
                    except api.models.KoliSonDurum.DoesNotExist:
                        messages.add_message(
                            request, messages.ERROR, 'Girilen güne ait veri bulunamadı.')
            elif request.method == 'GET':
                form = api.models.GunGetirForm()
            return render(request, 'dashboard/koli/kolirapor_sontumu.html', {'form': form, 'data': data})
    elif 'tarih' in request.GET.keys():
        pass
    elif 'detay' in request.GET.keys():
        pass
    # from: https://books.agiliq.com/projects/django-orm-cookbook/en/latest/select_some_fields.html
    # The only difference between 'only' and 'values' is 'only' also fetches the id
    # guess what: if you don't use 'only', get_mamul_model_display won't work. yeah, just try to live with that.
    koli_son_degisiklikler = api.models.KoliDegisiklik.objects.order_by(
        '-id').only('tarih', 'mamul_model', 'koli_turu', 'koli_adet')[:10]
    koli_son_durum_ = s.SingleRecordSerializer(
        api.models.KoliSonDurum.objects.latest('tarih'))
    return render(request, 'dashboard/koli/kolirapor.html', {'koli_son_degisiklikler': koli_son_degisiklikler, 'durum': koli_son_durum_})


@login_required
@group_required('editor')
def koliguncelle(request):
    api.models.KoliRestockFormset = forms.formset_factory(
        api.models.KoliRestockForm)
    if request.method == 'POST':
        formset = api.models.KoliRestockFormset(request.POST)
        if formset.is_valid():
            for form in formset:
                try:
                    record = api.models.KoliSonDurum.objects.latest('tarih')
                    new_value = form.cleaned_data['koli_adet'] - pickle.loads(vars(record)[form.cleaned_data['mamul_model']])[
                        form.cleaned_data['kalite']][form.cleaned_data['koli_turu']][form.cleaned_data['kolideki_mamul_adet']]
                except (KeyError, EOFError, api.models.KoliSonDurum.DoesNotExist):
                    new_value = form.cleaned_data['koli_adet']
                api.models.KoliDegisiklik.objects.create(
                    mamul_model=form.cleaned_data['mamul_model'],
                    koli_turu=form.cleaned_data['koli_turu'],
                    kolideki_mamul_adet=form.cleaned_data['kolideki_mamul_adet'],
                    kalite=form.cleaned_data['kalite'],
                    koli_adet=new_value,
                    notlar='Bu değişiklik Koli Güncelleme ekranından yapılmıştır.',

dashboard/templates/dashboard/hammadde/hammaddeeklecikar.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load dashboard_filters %}
{% block title %}Hammadde Ekle/Çıkar{% endblock %}
{% block icon %}pe-7s-paint-bucket icon-gradient bg-amy-crisp{% endblock %}
{% block pagetitle %}Hammadde Ekle/Çıkar{% endblock %}
{% block pagesubtitle %}Bu sayfadan stok içeriğine hammadde eklemesi ve çıkarması yapılır. {% endblock %}
{% block extracss %}
<link rel="stylesheet" href="{% static 'dashboard/chosen.css' %}">
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12 col-lg-6">
        <div class="mb-3 card">
            <div class="card-body">
                <h5 class="card-title">Hammadde Ekle / Çıkar</h5>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-lg">Kaydet</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-12 col-lg-6">
        <div class="mb-3 card">
            <div class="card-body">
                <h5 class="card-title">Son 10 Hammadde Girdi / Çıktı İşlemi</h5>
                <div class="scroll-area-lg">
                    <div class="scrollbar-container">
                        <ul class="rm-list-borders rm-list-borders-scroll list-group list-group-flush">
                        {% for row in son_on %}
                            <li class="list-group-item">
                                <div class="widget-content p-0">
                                    <div class="widget-content-wrapper">
                                        <div class="widget-content-left mr-3">
                                        {% if row.kullanici.profile.photo %}
                                            <img width="42" class="rounded-circle" src="/uploadedmedia/{{ row.kullanici.profile.photo }}" alt="">
                                        {% else %}
                                            <img width="42" class="rounded-circle" src="{% static 'dashboard/images/avatars/default_avatar.png' %}" alt="">
                                        {% endif %}
                                        </div>
                                        <div class="widget-content-left">
                                            <div class="widget-heading">{{ row.kullanici.get_full_name }}</div>
                                            <div class="widget-subheading">{{ row.kullanici.profile.title }}</div>
                                        </div>
                                        <div class="widget-content-right" data-toggle="tooltip" data-placement="bottom" data-original-title="Tarih: {{ row.tarih }}">
                                            <div class="font-size-xlg text-muted">
                                                <small class="pr-1">{{ row.get_madde_display }}</small>
                                                <span>{{ row.miktar|abs }}</span>
                                                <small class="text-{% if row.miktar < 0 %}danger{% else %}success{% endif %} pl-2">
                                                    <i class="fa fa-angle-{% if row.miktar < 0 %}down{% else %}up{% endif %}"></i>
                                                </small>
                                            </div>
                                        </div>
                                        <button class="ml-2 btn btn-danger" onclick="window.location.href = '{% url "dashboard:hammaddeeklecikar_sil" row.id %}';"><i class="pe-7s-trash"></i></button>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extrascript %}
<script src="{% static 'dashboard/scripts/chosen.jquery.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/scripts/chosen.init.js' %}" type="text/javascript"></script>
{% endblock %}

dashboard/templates/dashboard/hammadde/hammaddeeklecikar_sil.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load dashboard_filters %}
{% block title %}Hammadde İşlemi Sil{% endblock %}
{% block icon %}pe-7s-trash icon-gradient bg-love-kiss{% endblock %}
{% block pagetitle %}Hammadde İşlemi Sil{% endblock %}
{% block pagesubtitle %}Bu sayfadan daha önce girilmiş <a href="{% url 'dashboard:hammaddeeklecikar' %}">Hammadde Ekle / Çıkar</a> işlemi silinir. Bugün içinde yapılmamış işlemleri silemezsiniz.{% endblock %}
{% block content %}
<div class="card mb-3 widget-content">
    <div class="card-body">
        <h5 class="card-title">Bu Hammadde Ekle / Çıkar İşlemini Sil</h5>
        <div class="widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading">{{ record.get_madde_display }}</div>
                        <div class="widget-subheading">Madde</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading">{{ record.miktar }}</div>
                        <div class="widget-subheading">Miktar</div>
                    </div>
                </div>
            </div>
        </div>
        {% if record.notlar %}
        <div class="widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading">{{ record.notlar }}</div>
                        <div class="widget-subheading">Notlar</div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading">{{ record.tarih }}</div>
                        <div class="widget-subheading">Tarih</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading">{{ record.kullanici.get_full_name }}</div>
                        <div class="widget-subheading">Değişikliği Yapan</div>
                    </div>
                </div>
            </div>
        </div>
        <form method="POST">
            <button class="btn btn-outline-focus ml-3 mr-2" onclick="window.location.href = '{% url "dashboard:hammaddeeklecikar" %}';" type="button">&laquo; Geri Dön</button>
            {% csrf_token %}
            <button class="btn btn-danger" type="submit"><i class="pe-7s-trash"></i> Sil</button>
        </form>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/hammadde/hammaddeguncelle.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load dashboard_filters %}
{% block title %}Hammadde Stok Güncelle{% endblock %}
{% block icon %}pe-7s-paint-bucket icon-gradient bg-amy-crisp{% endblock %}
{% block pagetitle %}Hammadde Stok Güncelle{% endblock %}
{% block pagesubtitle %}Bu sayfadan hammadde stoğu güncellemesi yapılır. Buraya gireceğiniz veriler stoktaki son durumu temsil eder. Ekleme veya çıkarma yapmak için lütfen <a href="{% url 'dashboard:hammaddeeklecikar' %}">Hammadde Ekle / Çıkar</a> sayfasından işlem yapın.{% endblock %}
{% block extracss %}
<link rel="stylesheet" href="{% static 'dashboard/chosen.css' %}">
{% endblock %}
{% block content %}
<div class="mb-3 card">
    <div class="card-body">
        <h5 class="card-title">Hammadde Stok Güncelle</h5>
        <form method="POST">
            {% csrf_token %}
            {{ formset.management_form }}
            <table class="mb-0 table table-borderless">
                <thead>
                    <tr>
                        {% for field in formset.empty_form %}
                        <th>{{ field.label }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody id="formlar">
                    {% for form in formset %}
                    <tr id="formrow{{ forloop.counter0 }}">
                        {% for field in form %}
                        <td>{{ field.errors }}{{ field }}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <button type="button" class="ml-2 btn btn-success btn-lg" id="addmore">Satır Ekle</button>
            <button type="button" class="ml-2 btn btn-danger btn-lg" id="deleterow">Satır Sil</button>
            <button type="submit" class="ml-2 btn btn-primary btn-lg">Tümünü Kaydet</button>
        </form>
        <div id="emptyform" style="display: none;">
            <tr>
                {% for field in formset.empty_form %}
                <td>{{ field }}</td>
                {% endfor %}
                <td><button type="button" class="btn btn-danger btn-lg">Sil</button></td>
            </tr>
        </div>
    </div>
</div>
{% endblock %}
{% block extrascript %}
<script src="{% static 'dashboard/scripts/chosen.jquery.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/scripts/chosen.init.js' %}" type="text/javascript"></script>
<script type="text/javascript">
// from: https://simpleit.rocks/python/django/dynamic-add-form-with-add-button-in-django-modelformset-template/
$('#addmore').click(function() {
	var form_idx = $('#id_form-TOTAL_FORMS').val();
    var new_form_html = `
        <tr id="formrow__prefix__">
        {% for field in formset.empty_form %}
            <td>{{ field }}</td>
        {% endfor %}
        </tr>`;
	$('#formlar').append(new_form_html.replace(/__prefix__/g, form_idx));
	$('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);

    for (var selector in config) {
        $(selector).chosen(config[selector]);
    }
});

$('#deleterow').click(function() {
    var form_idx = parseInt($('#id_form-TOTAL_FORMS').val()) - 1;
    if (form_idx !== 0) {
        $('#formrow' + String(form_idx)).remove();
        $('#id_form-TOTAL_FORMS').val(parseInt(form_idx));
    }
});
</script>
{% endblock %}

dashboard/templates/dashboard/hammadde/hammadderapor.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load dashboard_filters %}
{% block title %}Hammadde Rapor{% endblock %}
{% block icon %}pe-7s-paint-bucket icon-gradient bg-amy-crisp{% endblock %}
{% block pagetitle %}Hammadde Rapor{% endblock %}
{% block pagesubtitle %}Hammadde Rapor{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-6">
        <div class="main-card mb-3 card">
            <div class="card-body">
                <h5 class="card-title">Hammadde Giriş Çıkışları</h5>
                <table class="mb-0 table table-hover">
                    <thead>
                        <tr>
                            <th>Tarih</th>
                            <th>Madde</th>
                            <th>Miktar</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for degisiklik in ham_son_degisiklikler %}
                        <tr>
                            <th scope="row">{{ degisiklik.tarih|date:'j/n/Y G:i' }}</th>
                            <td>{{ degisiklik.get_madde_display }}</td>
                            <td>{{ degisiklik.miktar }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <a href="{% url 'dashboard:hammadderapor' %}?istek=deg_tumu">Tümünü gör</a>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="main-card mb-3 card">
            <div class="card-body">
                <h5 class="card-title">Hammadde Stok Durumu</h5>
                <table class="mb-0 table table-hover">
                    <thead>
                        <tr>
                            <th>Maddeler</th>
                            <th>Tarih: {{ durum.tarih|date:'j/n/Y' }}</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for field in durum.fields %}
                        <tr>
                            <th colspan="2" style="text-align:center;">{{ field.0 }}</th>
                        </tr>
                        {% for material in field.1 %}
                        <tr>
                            <th>{{ material.0 }}</th>
                            <td>{{ material.1 }}</td>
                        </tr>
                    {% endfor %}{% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <a href="{% url 'dashboard:hammadderapor' %}?istek=son_tumu">Geçmiş bir gün için stok durumu sorgula</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/hammadde/hammadderapor_degtumu.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load dashboard_filters %}
{% block title %}Hammadde Rapor{% endblock %}
{% block icon %}pe-7s-paint-bucket icon-gradient bg-amy-crisp{% endblock %}
{% block pagetitle %}Hammadde Rapor{% endblock %}
{% block pagesubtitle %}Tüm Hammadde Giriş Çıkışları{% endblock %}
{% block content %}
<div class="main-card mb-3 card">
    <div class="card-body">
        <h5 class="card-title">Tüm Hammadde Giriş Çıkışları</h5>
        <table class="mb-0 table table-hover">
            <thead>
                <tr>
                    <th>Tarih</th>
                    <th>Madde</th>
                    <th>Miktar</th>
                    <th>Notlar</th>
                    <th>Değişikliği Yapan</th>
                </tr>
            </thead>
            <tbody>
            {% for degisiklik in data %}
                <tr>
                    <th scope="row">{{ degisiklik.tarih|date:'j/n/Y G:i' }}</th>
                    <td>{{ degisiklik.get_madde_display }}</td>
                    <td>{{ degisiklik.miktar }}</td>
                    <td>{% if degisiklik.notlar %}
                        <div class="widget-content-right" data-toggle="tooltip" data-placement="bottom" data-original-title="{{ degisiklik.notlar }}">
                        {{ degisiklik.notlar|truncatechars:10 }}
                        </div>{% endif %}
                    </td>
                    <td>{{ degisiklik.kullanici.get_full_name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/hammadde/hammadderapor_sontumu.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}Hammadde Rapor{% endblock %}
{% block icon %}pe-7s-paint-bucket icon-gradient bg-amy-crisp{% endblock %}
{% block pagetitle %}Hammadde Rapor{% endblock %}
{% block pagesubtitle %}Gün Bazlı Stok dataları{% endblock %}
{% block content %}
<div class="main-card mb-3 card">
    <div class="card-body">
        <h5 class="card-title">Gün Bazlı Stok dataları</h5>
        <form method="POST">{% csrf_token %}{{ form }}<button type="submit" class="btn btn-primary">Ara</button></form>
        {% if data %}
        <table class="mb-0 table table-hover">
            <thead>
                <tr>
                    <th>Modeller</th>
                    <th>Tarih: {{ data.tarih|date:'j/n/Y' }}</th>
                </tr>
            </thead>
            <tbody>
            {% for field in data.fields %}
                <tr>
                    <th colspan="2" style="text-align:center;">{{ field.0 }}</th>
                </tr>
                {% for product in field.1 %}
                <tr>
                    <th>{{ product.0 }}</th>
                    <td>{{ product.1 }}</td>
                </tr>
            {% endfor %}{% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}
{% block extrascript %}
<script type="text/javascript">
$(document).ready(function(event) {
    $('#id_gun').attr('type','date')
});
</script>
{% endblock %}